=== usnistgov/metaschema-java/metaschema-java-codegen/src/test/resources/metaschema/fields_with_flags/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:m="http://csrc.nist.gov/ns/oscal/metaschema/1.0"
           xmlns:complex-field="http://csrc.nist.gov/ns/metaschema/testing/fields/with/flags"
           xmlns:oscal-prose="http://csrc.nist.gov/ns/metaschema/testing/fields/with/flags"
           elementFormDefault="qualified"
           targetNamespace="http://csrc.nist.gov/ns/metaschema/testing/fields/with/flags"
           version="1.0">
   <xs:annotation>
      <xs:appinfo>
         <m:schema-name>Metaschema with complex field</m:schema-name>
         <m:schema-version>1.0</m:schema-version>
         <m:short-name>complex-field</m:short-name>
         <m:root>top-level</m:root>
      </xs:appinfo>
   </xs:annotation>
   <xs:element name="top-level" m:root="yes">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Root</m:formal-name>
            <m:description>Root assembly</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Root</b>: Root assembly</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="complex-field:complex-field1" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="complex-field:complex-field2"
                        minOccurs="1"
                        maxOccurs="unbounded"/>
            <xs:element name="complex-fields3" minOccurs="1" maxOccurs="1">
               <xs:annotation>
                  <xs:appinfo>
                     <m:formal-name>Complex Field 3</m:formal-name>
                     <m:description>A complex field with a flag</m:description>
                  </xs:appinfo>
                  <xs:documentation>
                     <b>Complex Field 3</b>: A complex field with a flag</xs:documentation>
               </xs:annotation>
               <xs:complexType>
                  <xs:sequence>
                     <xs:element ref="complex-field:complex-field3"
                                 minOccurs="2"
                                 maxOccurs="unbounded"/>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
            <xs:element ref="complex-field:complex-field4"
                        minOccurs="0"
                        maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attribute name="id" type="xs:string">
            <xs:annotation>
               <xs:appinfo>
                  <m:formal-name>Identifier</m:formal-name>
                  <m:description>The document identifier</m:description>
               </xs:appinfo>
               <xs:documentation>
                  <b>Identifier</b>: The document identifier</xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
      <xs:unique name="top-level-complex-field4-keys">
         <xs:selector xpath="complex-field:complex-field4"/>
         <xs:field xpath="@id2"/>
      </xs:unique>
   </xs:element>
   <xs:element name="complex-field1">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Complex Field 1</m:formal-name>
            <m:description>A complex field with a flag</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Complex Field 1</b>: A complex field with a flag</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="id" type="xs:string">
                  <xs:annotation>
                     <xs:appinfo>
                        <m:formal-name>Identifier</m:formal-name>
                        <m:description>The document identifier</m:description>
                     </xs:appinfo>
                     <xs:documentation>
                        <b>Identifier</b>: The document identifier</xs:documentation>
                  </xs:annotation>
               </xs:attribute>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="complex-field2">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Complex Field 1</m:formal-name>
            <m:description>A complex field with a flag</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Complex Field 1</b>: A complex field with a flag</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="id" type="xs:string">
                  <xs:annotation>
                     <xs:appinfo>
                        <m:formal-name>Identifier</m:formal-name>
                        <m:description>The document identifier</m:description>
                     </xs:appinfo>
                     <xs:documentation>
                        <b>Identifier</b>: The document identifier</xs:documentation>
                  </xs:annotation>
               </xs:attribute>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="complex-field3">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Complex Field 3</m:formal-name>
            <m:description>A complex field with a flag</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Complex Field 3</b>: A complex field with a flag</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="id2" type="xs:string">
                  <xs:annotation>
                     <xs:appinfo>
                        <m:formal-name>A flag</m:formal-name>
                        <m:description>A simple flag</m:description>
                     </xs:appinfo>
                     <xs:documentation>
                        <b>A flag</b>: A simple flag</xs:documentation>
                  </xs:annotation>
               </xs:attribute>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
   <xs:element name="complex-field4">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Complex Field 4</m:formal-name>
            <m:description>A complex field with a flag</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Complex Field 4</b>: A complex field with a flag</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="id2" use="required" type="xs:string">
                  <xs:annotation>
                     <xs:appinfo>
                        <m:formal-name>A flag</m:formal-name>
                        <m:description>A simple flag</m:description>
                     </xs:appinfo>
                     <xs:documentation>
                        <b>A flag</b>: A simple flag</xs:documentation>
                  </xs:annotation>
               </xs:attribute>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== usnistgov/metaschema-java/metaschema-java-codegen/src/test/resources/metaschema/fields_with_flags/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<top-level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://csrc.nist.gov/ns/metaschema/testing/fields/with/flags schema.xsd"
  xmlns="http://csrc.nist.gov/ns/metaschema/testing/fields/with/flags" id="test">
  <complex-field1 id="complex-field1">test-string</complex-field1>
  <complex-field2 id="complex-field2-1">test-string2</complex-field2>
  <complex-fields3>
    <complex-field3 id2="complex-field3-1">test-string3</complex-field3>
    <complex-field3 id2="complex-field3-2">test-string4</complex-field3>
  </complex-fields3>
  <complex-field4 id2="complex-field4-1">test-string5</complex-field4>
  <complex-field4 id2="complex-field4-2">test-string6</complex-field4>
</top-level>
