=== usnistgov/metaschema-java/metaschema-java-codegen/src/test/resources/metaschema/assembly/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:m="http://csrc.nist.gov/ns/oscal/metaschema/1.0"
           xmlns:assembly="http://csrc.nist.gov/ns/metaschema/testing/assembly"
           xmlns:oscal-prose="http://csrc.nist.gov/ns/metaschema/testing/assembly"
           elementFormDefault="qualified"
           targetNamespace="http://csrc.nist.gov/ns/metaschema/testing/assembly"
           version="1.0">
   <xs:annotation>
      <xs:appinfo>
         <m:schema-name>Metaschema with assembly</m:schema-name>
         <m:schema-version>1.0</m:schema-version>
         <m:short-name>assembly</m:short-name>
         <m:root>top-level</m:root>
      </xs:appinfo>
   </xs:annotation>
   <xs:element name="top-level" m:root="yes">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Root</m:formal-name>
            <m:description>Root assembly</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Root</b>: Root assembly</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="assembly:child" minOccurs="1" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attribute name="id" type="xs:string">
            <xs:annotation>
               <xs:appinfo>
                  <m:formal-name>Identifier</m:formal-name>
                  <m:description>The document identifier</m:description>
               </xs:appinfo>
               <xs:documentation>
                  <b>Identifier</b>: The document identifier</xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="child">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Child</m:formal-name>
            <m:description>Child assembly</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Child</b>: Child assembly</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="assembly:grandchild" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="grandchildren2" minOccurs="1" maxOccurs="1">
               <xs:annotation>
                  <xs:appinfo>
                     <m:formal-name>Child</m:formal-name>
                     <m:description>Child assembly</m:description>
                  </xs:appinfo>
                  <xs:documentation>
                     <b>Child</b>: Child assembly</xs:documentation>
               </xs:annotation>
               <xs:complexType>
                  <xs:sequence>
                     <xs:element ref="assembly:grandchild" minOccurs="1" maxOccurs="unbounded"/>
                  </xs:sequence>
               </xs:complexType>
            </xs:element>
            <xs:element ref="assembly:grandchild" minOccurs="1" maxOccurs="1"/>
         </xs:sequence>
         <xs:attribute name="id" use="required" type="xs:string">
            <xs:annotation>
               <xs:appinfo>
                  <m:formal-name>Identifier</m:formal-name>
                  <m:description>The document identifier</m:description>
               </xs:appinfo>
               <xs:documentation>
                  <b>Identifier</b>: The document identifier</xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="grandchild">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Child</m:formal-name>
            <m:description>Child assembly</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Child</b>: Child assembly</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="assembly:field" minOccurs="0" maxOccurs="unbounded"/>
         </xs:sequence>
         <xs:attribute name="id" type="xs:string">
            <xs:annotation>
               <xs:appinfo>
                  <m:formal-name>Identifier</m:formal-name>
                  <m:description>The document identifier</m:description>
               </xs:appinfo>
               <xs:documentation>
                  <b>Identifier</b>: The document identifier</xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="field">
      <xs:annotation>
         <xs:appinfo>
            <m:formal-name>Complex Field</m:formal-name>
            <m:description>A complex field with a flag</m:description>
         </xs:appinfo>
         <xs:documentation>
            <b>Complex Field</b>: A complex field with a flag</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:simpleContent>
            <xs:extension base="xs:string">
               <xs:attribute name="id" type="xs:string">
                  <xs:annotation>
                     <xs:appinfo>
                        <m:formal-name>Identifier</m:formal-name>
                        <m:description>The document identifier</m:description>
                     </xs:appinfo>
                     <xs:documentation>
                        <b>Identifier</b>: The document identifier</xs:documentation>
                  </xs:annotation>
               </xs:attribute>
            </xs:extension>
         </xs:simpleContent>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== usnistgov/metaschema-java/metaschema-java-codegen/src/test/resources/metaschema/assembly/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<top-level xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://csrc.nist.gov/ns/metaschema/testing/assembly schema.xsd"
  xmlns="http://csrc.nist.gov/ns/metaschema/testing/assembly" id="test">
  <child id="child1">
    <grandchild id="singleton-ungrouped">
      <field id="field1">value1</field>
    </grandchild>
    <grandchildren2>
      <grandchild id="multiple-grouped-1">
        <field id="field2a">value2a</field>
      </grandchild>
      <grandchild id="multiple-grouped-2">
        <field id="field2b">value2b</field>
      </grandchild>
    </grandchildren2>
    <grandchild id="single-1">
      <field id="field3">value3</field>
    </grandchild>
  </child>
  <child id="child2">
    <grandchild id="multiple-ungrouped-1">
      <!-- comment -->
      <field id="field4">value4</field>
    </grandchild>
    <grandchild id="multiple-ungrouped-2">
      <field id="field5">value5</field>
    </grandchild>
    <grandchildren2>
      <grandchild id="multiple-grouped-3">
        <field id="field6">value6</field>
      </grandchild>
      <grandchild id="multiple-grouped-4">
        <field id="field7">value7</field>
      </grandchild>
    </grandchildren2>
    <grandchild id="single-2">
      <field id="field8">value8</field>
    </grandchild>
  </child>
</top-level>
